FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source code
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Start the server
CMD [ "node", "server.js" ]
